### ISSUE TITLE
Select window by handle

### ISSUE THREAD

**Issue by igaisin** [robocorp/java-access-bridge-wrapper#6]
I need to select window by hwnd parameter, it is more convenient to test multiple windows with the same titles

**Comment by mmokko** [comment]
Hello @igaisin, I agree this is definitely a valid feature request. I'm afraid I cannot get this done before next month, unfortunately I'm quite busy on other tasks currently.

I would be happy to take pull request if you are eager to get this done asap. I can make a new release once the feature is merged.

**Comment by igaisin** [comment]
I did something similar, but noticed a memory leak when reading windows handle or title, run in an infinite loop. 

a 2mb memory jump occurs when an action is performed. Everything is fine during downtime.
I noticed Java application memory leak too, but not so fast.
Java application is third party. 
Could the JAB be leaking from a third party application. Or is it a JAB bug?

Later I will prepare and share code examples

**Comment by igaisin** [comment]
> I did something similar, but noticed a memory leak when reading windows handle or title, run in an infinite loop.
> 
> a 10-15 MB memory jump occurs when an action is performed. Everything is fine during downtime.
> I noticed Java application memory leak too, but not so fast.
> Java application is third party.
> Could the JAB be leaking from a third party application. Or is it a JAB bug?
> 
> Later I will prepare and share code examples

Solved a problem, after each window, before the new definition, you need to write jab_wrapper.shutdown() for clear memory
